---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mengxingdong.
--- DateTime: 2018/7/26 下午2:26
---



ActorTable = ActorTable or {}

local TAG = "ACTOR TABLE"

function ActorTable:createDirector()
    ActorTable.director = xe.Director:GetInstance()

    commentUtils.printLog(TAG.."Director GetInstance", ActorTable.director)

end

function ActorTable:createScene(scenceName)

    ActorTable.scene = xe.Scene:CreateScene(scenceName)

    commentUtils.printLog(TAG.."创建scene", ActorTable.scene)

end


function ActorTable:createWorld(scene)
    if scene ~= nil
    then
        ActorTable.world = scene:GetWorld()
        commentUtils.printLog(TAG.."创建world", ActorTable.world)
    end

end
--
function ActorTable:createCameraActor(worldName)
    if ActorTable.world ~= nil then
        ActorTable.cameraActor, ActorTable.cameraCompent = ActorTable.world:CreateActor(XECameraActor.ACTOR_TYPENAME, worldName)


        commentUtils.printLog(TAG.."xtype", ActorTable.cameraCompent.XType)

        ActorTable.camera = ActorTable.cameraCompent:SetAsPerspectiveCamera()

        local success = ActorTable.cameraCompent:ApplyAsSystemCamera()
        local camera = ActorTable.director:GetWindow():GetViewport():GetWorkCamera()

        commentUtils.printLog(TAG.."-cameraActor-ApplyAsSystemCamera-success:", success)
        commentUtils.printLog(TAG.."-cameraActor", ActorTable.cameraActor)
        commentUtils.printLog(TAG.."-cameraCompent", ActorTable.cameraCompent)
        commentUtils.printLog(TAG.."-camera(in actor)", ActorTable.camera)
        commentUtils.printLog(TAG.."-camera(in viewport)", camera)
    end

end
-- 设置相机的位置
function ActorTable:setCameraPosition(positionV3)
    ActorTable.camera:SetPos(positionV3)
    commentUtils.printLog(TAG.."设置相机位置position", positionV3)
end

-- 相机观察方向与相机顶端位置
function ActorTable:setCameraDirectionAndUp(direction, uption)
    ActorTable.camera:SetDirAndUp(direction, uption)
    commentUtils.printLog(TAG.."设置相机方向direction", direction)
    commentUtils.printLog(TAG.."设置相机up", uption)
end
-- 设置摄像头的近平面和远平面
function ActorTable:setCameraZNearFar(near, far)
    ActorTable.camera:SetZNearFar(near, far)
    commentUtils.printLog(TAG.."设置摄像头的近平面和远平面")
end

function ActorTable:setCameraFOV(angle)
    ActorTable.camera:SetFOV(angle)
    commentUtils.printLog(TAG.."设置FOV", angle)
end

function ActorTable:directorAttachCamera(director, camera)

    if director ~= nil and camera ~= nil then
        director:GetWindow():GetViewport():AttachCamera(camera)
        commentUtils.printLog(TAG.."设置attach camera")
    end
end

function ActorTable:directorViewPortResize(director)
    if director ~= nil
    then
        director:GetWindow():GetViewport():Resize()
        commentUtils.printLog(TAG.."设置 view port resize")
    end
end