---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by momo.
--- DateTime: 2018/7/31 下午3:36
---

isDebug = true

modelInfo = modelInfo or {}

clickLock = clickLock or false

globalClickActive = globalClickActive or false

isMovingToRealPlane = isMovingToRealPlane or false

isPlayingInstruction = isPlayingInstruction or false

-- 判断模型是否再装扮状态
modelInDressState = false

phoneIsUpward = nil

isAppeared = isAppeared or false